spring:
  application:
    name: authserver
  web:
    error:
      whitelabel:
        enabled: false
      include-message: always
      include-binding-errors: always

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    use-root-path: true

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  expire-hours: ${JWT_EXPIRE_HOURS}
  admin-expire-hours: ${JWT_ADMIN_EXPIRE_HOURS}